[package]
name = "proxirun"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
proxirun="_"

[dev-addresses]
proxirun="0xdeadbeef"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


