[package]
name = "proxirun"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
proxirun="0x9476528b38675eaf7fcc4d18c9472f22efd24532cad25a27794c6f7300df06cc"

[dev-addresses]
proxirun="0xdeadbeef"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


